### ISSUE TITLE
Release et documentation

### ISSUE THREAD

**Issue by jadegrli** [gen-classroom/projet-vallon_groeli_gonzalezleon#28]
En tant qu’utilisateur, j’aimerai qu’une release du générateur de site statique soit téléchargeabledepuis l’onglet release de GitHub. Untag git (v0.0.1) correspondant à la release doit êtrepublié. La release doit également être accompagnée d’instructions d’installation reproductible.

**Comment by DavidGL17** [comment]
Faite, voir release sur github
